CAR-125 added edit/save rules functional
multicora/car-towing pull request #15
Opened 2016-09-14 11:49 UTC by FeditskiyRoman

2016-09-17 10:16 UTC, dmitrij-borchuk commented on dev/publicDev/managers-page/data.service.js
>        // TODO: future update functionality
Remove it

2016-09-17 10:18 UTC, dmitrij-borchuk commented on dev/publicDev/managers-page/managers-controller.js
> +    vm.edit = function(index) {
Do not use 'index', pass 'rule' to the function

2016-09-17 10:19 UTC, dmitrij-borchuk commented on dev/publicDev/managers-page/managers-controller.js
> +    vm.save = function(index, id, rule) {
Do not use 'index', pass 'rule' to the function

2016-09-17 10:19 UTC, dmitrij-borchuk commented on dev/publicDev/managers-page/style.scss
> +  .btn-block+.btn-block {
Do not use '+'

2016-09-17 10:20 UTC, dmitrij-borchuk requested changes

2016-09-19 08:10 UTC, FeditskiyRoman commented on dev/publicDev/managers-page/data.service.js
>        // TODO: future update functionality
fixed

2016-09-19 08:10 UTC, FeditskiyRoman commented on dev/publicDev/managers-page/managers-controller.js
> +    vm.edit = function(index) {
fixed

2016-09-19 08:10 UTC, FeditskiyRoman commented on dev/publicDev/managers-page/managers-controller.js
> +    vm.save = function(index, id, rule) {
fixed

2016-09-19 08:10 UTC, FeditskiyRoman commented on dev/publicDev/managers-page/style.scss
> +  .btn-block+.btn-block {
fixed

2016-09-20 20:21 UTC, merged