CART-50 added ui and logical part for admin employees
multicora/car-towing pull request #21
Opened 2016-09-19 15:00 UTC by FeditskiyRoman

2016-09-20 20:41 UTC, dmitrij-borchuk commented on dev/publicDev/admin.employees/style.scss
> +      text-overflow: ellipsis;
Use class ".ellipsis"

2016-09-20 20:43 UTC, dmitrij-borchuk commented on dev/routing/users.js
> +          permissions: ['users:read']
Should be "users:write"

2016-09-20 20:43 UTC, dmitrij-borchuk commented on dev/routing/users.js
> +          permissions: ['users:read']
Should be "users:write"

2016-09-20 20:43 UTC, dmitrij-borchuk commented on dev/routing/users.js
> +          permissions: ['users:read']
Should be "users:write"

2016-09-20 20:44 UTC, dmitrij-borchuk requested changes

2016-09-21 07:11 UTC, FeditskiyRoman commented on dev/routing/users.js
> +          permissions: ['users:read']
fixed

2016-09-21 07:11 UTC, FeditskiyRoman commented on dev/routing/users.js
> +          permissions: ['users:read']
fixed

2016-09-21 07:11 UTC, FeditskiyRoman commented on dev/routing/users.js
> +          permissions: ['users:read']
fixed

2016-09-21 07:24 UTC, FeditskiyRoman commented on dev/publicDev/admin.employees/style.scss
> +      text-overflow: ellipsis;
fixed

2016-09-22 19:58 UTC, merged