CART-124 added 1366px width
multicora/car-towing pull request #26
Opened 2016-09-22 09:43 UTC by FeditskiyRoman

2016-09-22 20:07 UTC, dmitrij-borchuk commented on dev/publicDev/property.page/propertyPage.jade
> +div.property-page..admin-page
Why "..admin-page"

2016-09-22 20:08 UTC, dmitrij-borchuk requested changes

2016-09-22 20:08 UTC, dmitrij-borchuk commented
Plese, resolve conflicts

2016-09-23 07:58 UTC, FeditskiyRoman commented on dev/publicDev/property.page/propertyPage.jade
> +div.property-page..admin-page
fixed

2016-09-23 20:18 UTC, dmitrij-borchuk approved these changes

2016-09-23 20:18 UTC, merged