CART-119 added service for checking user
multicora/car-towing pull request #30
Opened 2016-09-26 09:31 UTC by FeditskiyRoman

2016-09-28 11:02 UTC, dmitrij-borchuk requested changes

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/publicDev/admin.employees/config.js
> +          resolver: resolver.get2('see-admin-page')
Rename

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/publicDev/admin.employees/config.js
> +          resolver: resolver.get2('see-admin-page')
Rename

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/publicDev/admin.employees/config.js
> +          resolver: resolver.get2('see-admin-page')
Rename

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/publicDev/admin.got-towed/config.js
> +        resolver: resolver.get2('see-admin-page')
Rename

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/publicDev/mainpage/homeConfig,js.js
> +        resolver: resolver.get2()
Rename

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/publicDev/managers-page/managers-config.js
> +      resolver: resolver.get2('see-manager-page')
Rename

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/publicDev/scripts/resolver.js
> +    this.get2 = function (action) {
Rename

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/publicDev/scripts/resolver.js
>      this.get = function () {
remove

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/publicDev/scripts/userCheckingService.js
> +'use strict';
Chech identation

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/publicDev/scripts/userCheckingService.js
> +          usersActions = usersActions.concat(rolesMap[roles.name].actions[0].name);
Why only first action? (.actions[0])

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/routing/actions.js
> +const Joi = require('joi');
What for?

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/routing/actions.js
> +const Boom = require('boom');
What for?

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/routing/actions.js
> +const path = require('path');
What for?

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/routing/actions.js
> +        DAL.users.createUser(request.payload, function (err, docs) {
"DAL.users.createUser" ???????

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/routing/actions.js
> +  server.route({
What for this route?

2016-09-28 11:02 UTC, dmitrij-borchuk commented on dev/server.js
> +  server.connection( {port: 8080, routes: {cors: {origin: ['*'],credentials : true}}} );
What for?

2016-09-28 14:34 UTC, RomanFedytskyi commented on dev/publicDev/admin.employees/config.js
> +          resolver: resolver.get2('see-admin-page')
fixed

2016-09-28 14:34 UTC, FeditskiyRoman commented on dev/publicDev/admin.employees/config.js
> +          resolver: resolver.get2('see-admin-page')
fixed

2016-09-28 14:34 UTC, FeditskiyRoman commented on dev/publicDev/admin.employees/config.js
> +          resolver: resolver.get2('see-admin-page')
fixed

2016-09-28 14:35 UTC, FeditskiyRoman commented on dev/publicDev/admin.got-towed/config.js
> +        resolver: resolver.get2('see-admin-page')
fixed

2016-09-28 14:35 UTC, FeditskiyRoman commented on dev/publicDev/mainpage/homeConfig,js.js
> +        resolver: resolver.get2()
fixed

2016-09-28 14:35 UTC, FeditskiyRoman commented on dev/publicDev/scripts/resolver.js
> +    this.get2 = function (action) {
fixed

2016-09-28 14:35 UTC, FeditskiyRoman commented on dev/publicDev/scripts/resolver.js
>      this.get = function () {
fixed

2016-09-28 14:35 UTC, FeditskiyRoman commented on dev/publicDev/scripts/userCheckingService.js
> +          usersActions = usersActions.concat(rolesMap[roles.name].actions[0].name);
fixed

2016-09-28 14:35 UTC, FeditskiyRoman commented on dev/routing/actions.js
> +const Boom = require('boom');
fixed

2016-09-28 14:35 UTC, FeditskiyRoman commented on dev/routing/actions.js
> +  server.route({
fixed

2016-09-28 14:35 UTC, FeditskiyRoman commented on dev/server.js
> +  server.connection( {port: 8080, routes: {cors: {origin: ['*'],credentials : true}}} );
fixed

2016-09-29 21:43 UTC, vetalcore requested changes

2016-09-29 21:43 UTC, vetalcore commented on dev/publicDev/scripts/userCheckingService.js
> +        // }
remove comments or  write some explanation (TODO)

2016-09-29 21:43 UTC, vetalcore commented on dev/publicDev/scripts/userCheckingService.js
> +})();
dont use angular directly in IIFE block
should be smthing like:
(function(NG, window, whatever){
    //body
})(angular, window, whatever)

2016-09-29 21:43 UTC, vetalcore commented on dev/publicDev/scripts/userCheckingService.js
> +        } else {
rewrite using **} else if (condition) {** instead of  **} else { if (condition)**

2016-09-29 22:01 UTC, vetalcore reviewed
wrap everything onto IIFE blocks to eliminate global scope polutting
dont use angular directly in IIFE blocks (pass it throught props)

2016-09-29 22:01 UTC, vetalcore commented on dev/publicDev/admin.parkingProblem/config.js
> +        resolver: resolver.get('see-admin-page')
'see-admin-page' -> move to some var

2016-09-29 22:01 UTC, vetalcore commented on dev/publicDev/admin.properties/config.js
> +          resolver: resolver.get('see-admin-page')
'see-admin-page' -> move to some var

2016-09-29 22:01 UTC, vetalcore commented on dev/publicDev/admin.properties/config.js
> +          resolver: resolver.get('see-admin-page')
'see-admin-page' -> move to some var

2016-09-29 22:01 UTC, vetalcore commented on dev/publicDev/scripts/resolver.js
> +              resolve();
resolve(); -> replace with promise's reject method

2016-09-29 22:01 UTC, vetalcore commented on dev/publicDev/scripts/resolver.js
>  (function() {
pass angular as a props

2016-09-29 22:12 UTC, dmitrij-borchuk commented on dev/publicDev/scripts/resolver.js
> +              resolve();
If user haven't loginned yet, we reseive the error as response on 'currentUser' reques.
This is resolver, it should be resolved even if error appears.

2016-09-30 08:59 UTC, FeditskiyRoman commented on dev/publicDev/managers-page/managers-config.js
> +      resolver: resolver.get2('see-manager-page')
fixed

2016-09-30 08:59 UTC, FeditskiyRoman commented on dev/publicDev/scripts/userCheckingService.js
> +'use strict';
fixed

2016-09-30 09:00 UTC, FeditskiyRoman commented on dev/routing/actions.js
> +const path = require('path');
fixed

2016-09-30 09:00 UTC, FeditskiyRoman commented on dev/routing/actions.js
> +const Joi = require('joi');
fixed

2016-09-30 09:00 UTC, FeditskiyRoman commented on dev/routing/actions.js
> +        DAL.users.createUser(request.payload, function (err, docs) {
fixed

2016-09-30 09:28 UTC, FeditskiyRoman commented on dev/publicDev/admin.parkingProblem/config.js
> +        resolver: resolver.get('see-admin-page')
fixed

2016-09-30 09:28 UTC, FeditskiyRoman commented on dev/publicDev/admin.properties/config.js
> +          resolver: resolver.get('see-admin-page')
fixed

2016-09-30 09:28 UTC, FeditskiyRoman commented on dev/publicDev/admin.properties/config.js
> +          resolver: resolver.get('see-admin-page')
fixed

2016-09-30 09:28 UTC, FeditskiyRoman commented on dev/publicDev/scripts/resolver.js
>  (function() {
fixed

2016-09-30 09:28 UTC, FeditskiyRoman commented on dev/publicDev/scripts/resolver.js
>  (function() {
fixed

2016-09-30 09:28 UTC, FeditskiyRoman commented on dev/publicDev/admin.properties/config.js
> +          resolver: resolver.get('see-admin-page')
fixed

2016-10-03 08:51 UTC, FeditskiyRoman commented on dev/publicDev/scripts/userCheckingService.js
> +        // }
fixed

2016-10-03 08:51 UTC, FeditskiyRoman commented on dev/publicDev/scripts/userCheckingService.js
> +        } else {
fixed

2016-10-03 08:51 UTC, FeditskiyRoman commented on dev/publicDev/scripts/userCheckingService.js
> +})();
fixed

2016-10-03 10:38 UTC, merged