CART-39 added complaint popup
multicora/car-towing pull request #34
Opened 2016-09-29 13:24 UTC by FeditskiyRoman

2016-10-03 20:58 UTC, vetalcore requested changes
resolve review changes

2016-10-03 20:58 UTC, vetalcore commented on dev/publicDev/Complaint/config.js
> +'use strict';
wrap into IIFE block with passed params

2016-10-03 20:58 UTC, vetalcore commented on dev/publicDev/Complaint/ctrl.js
> +(() => {
arrow functions dont work in FF etc, replace with function() {} ...

2016-10-03 20:58 UTC, vetalcore commented on dev/publicDev/Complaint/ctrl.js
> +"use strict";
follow the same convention for file names (complaintController or complaint-controller)...

2016-10-03 20:58 UTC, vetalcore commented on dev/publicDev/Complaint/ctrl.js
> +            console.log(res.data);
remove console statement

2016-10-03 20:58 UTC, vetalcore commented on dev/publicDev/Complaint/service.js
> +})();
pass angular as param

2016-10-03 20:58 UTC, vetalcore commented on dev/publicDev/Complaint/style.scss
> +        .name,
group with some general class name

2016-10-03 20:58 UTC, vetalcore commented on dev/publicDev/Complaint/style.scss
> +.complaint {
try to use bootstrap

2016-10-04 08:23 UTC, FeditskiyRoman commented on dev/publicDev/Complaint/config.js
> +'use strict';
fixed

2016-10-04 08:23 UTC, RomanFedytskyi commented on dev/publicDev/Complaint/ctrl.js
> +"use strict";
fixed

2016-10-04 08:23 UTC, FeditskiyRoman commented on dev/publicDev/Complaint/ctrl.js
> +(() => {
fixed

2016-10-04 08:24 UTC, FeditskiyRoman commented on dev/publicDev/Complaint/ctrl.js
> +            console.log(res.data);
fixed

2016-10-04 08:24 UTC, FeditskiyRoman commented on dev/publicDev/Complaint/service.js
> +})();
fixed

2016-10-10 07:59 UTC, FeditskiyRoman commented on dev/publicDev/Complaint/style.scss
> +        .name,
fixed

2016-10-10 07:59 UTC, FeditskiyRoman commented on dev/publicDev/Complaint/style.scss
> +.complaint {
fixed

2016-10-13 21:10 UTC, vetalcore approved these changes

2016-10-13 21:10 UTC, merged