Feature/cart 142 property deletion
multicora/car-towing pull request #39
Opened 2016-10-04 10:38 UTC by FeditskiyRoman

2016-10-12 22:09 UTC, dmitrij-borchuk requested changes

2016-10-12 22:09 UTC, dmitrij-borchuk commented on dev/publicDev/admin.properties/style.scss
>      button {
Please move, this to common place and use css class

2016-10-12 22:09 UTC, dmitrij-borchuk commented on dev/publicDev/admin.properties/tpl.jade
> +              ng-hide="rule.editmode"
Rule?

2016-10-13 09:19 UTC, RomanFedytskyi commented on dev/publicDev/admin.properties/style.scss
>      button {
fixed

2016-10-13 09:19 UTC, FeditskiyRoman commented on dev/publicDev/admin.properties/tpl.jade
> +              ng-hide="rule.editmode"
fixed

2016-10-13 11:47 UTC, dmitrij-borchuk approved these changes

2016-10-13 11:48 UTC, merged