Feature/cart 132 loading spinner
multicora/car-towing pull request #40
Opened 2016-10-05 11:11 UTC by FeditskiyRoman

2016-10-12 22:15 UTC, dmitrij-borchuk requested changes

2016-10-12 22:15 UTC, dmitrij-borchuk commented on dev/publicDev/scripts/Interseptor.js
> +      var loadingMessage = {
Please add response error handler

2016-10-13 10:41 UTC, FeditskiyRoman commented on dev/publicDev/scripts/Interseptor.js
> +      var loadingMessage = {
fixed

2016-10-13 21:18 UTC, vetalcore approved these changes

2016-10-13 21:18 UTC, merged