CART-154 added popup
multicora/car-towing pull request #41
Opened 2016-10-07 12:08 UTC by FeditskiyRoman

2016-10-12 22:18 UTC, dmitrij-borchuk commented
Please see screenshot http://prntscr.com/ct4hs3

2016-10-12 22:21 UTC, dmitrij-borchuk commented
I tried to add decal
See screenshot http://prntscr.com/ct4ior

2016-10-12 22:25 UTC, dmitrij-borchuk requested changes

2016-10-12 22:25 UTC, dmitrij-borchuk commented on dev/publicDev/decal/decalAdd.jade
> +            span.color White
Click on label should set the radio batton

2016-10-13 10:18 UTC, FeditskiyRoman commented on dev/publicDev/decal/decalAdd.jade
> +            span.color White
fixed

2016-10-13 21:27 UTC, vetalcore approved these changes
please resolve conflicts with dev, (if all issues are fixed)

2016-10-24 11:35 UTC, dmitrij-borchuk approved these changes

2016-10-24 11:36 UTC, merged