Cart 146 markup for unique users counter
multicora/car-towing pull request #49
Opened 2016-10-27 13:05 UTC by FeditskiyRoman

2016-11-02 20:47 UTC, dmitrij-borchuk requested changes

2016-11-02 20:47 UTC, dmitrij-borchuk commented on dev/publicDev/index.jade
> +      p Hit
Remove "hit" and "page view" because we don't have this information

2016-11-02 20:47 UTC, dmitrij-borchuk commented on dev/publicDev/index.jade
> +    .visitors
Remove this counter from all page except "home"

2016-11-03 09:43 UTC, FeditskiyRoman commented on dev/publicDev/index.jade
> +    .visitors
fixed

2016-11-03 09:43 UTC, FeditskiyRoman commented on dev/publicDev/index.jade
> +      p Hit
fixed

2016-12-02 16:40 UTC, dmitrij-borchuk approved these changes

2016-12-02 16:40 UTC, merged