Cart267 blocked property
multicora/car-towing pull request #76
Opened 2017-01-31 13:05 UTC by FeditskiyRoman

2017-02-05 17:43 UTC, dmitrij-borchuk requested changes

2017-02-05 17:43 UTC, dmitrij-borchuk commented on dev/publicDev/properties/properties.jade
> +          ng-if="!property.blocked"
Remove it

2017-02-06 08:59 UTC, FeditskiyRoman commented on dev/publicDev/properties/properties.jade
> +          ng-if="!property.blocked"
fixed

2017-02-12 11:51 UTC, dmitrij-borchuk approved these changes

2017-02-12 11:51 UTC, merged