Cart 282 bloking towing notification
multicora/car-towing pull request #77
Opened 2017-02-01 08:57 UTC by FeditskiyRoman

2017-02-05 17:45 UTC, dmitrij-borchuk requested changes

2017-02-05 17:45 UTC, dmitrij-borchuk commented on dev/routing/blocking.js
> +            !err ? reply(towingBlockingService.sendNotification(request.params.propertyId, property.name, request.auth.credentials.email)) : reply(Boom.badImplementation(err));
Line is too long

2017-02-06 09:14 UTC, FeditskiyRoman commented on dev/routing/blocking.js
> +            !err ? reply(towingBlockingService.sendNotification(request.params.propertyId, property.name, request.auth.credentials.email)) : reply(Boom.badImplementation(err));
fixed

2017-02-12 11:56 UTC, dmitrij-borchuk requested changes

2017-02-12 11:56 UTC, dmitrij-borchuk commented on dev/routing/blocking.js
> +            !err ? reply(towingBlockingService.sendNotification(
"towingBlockingService.sendNotification" returns promise. Promose should not be parameter of "reply"

2017-02-14 10:32 UTC, FeditskiyRoman commented on dev/routing/blocking.js
> +            !err ? reply(towingBlockingService.sendNotification(
fixed

2017-02-16 10:14 UTC, dmitrij-borchuk approved these changes

2017-02-16 10:16 UTC, merged