CART-175 added emergency Towing property
multicora/car-towing pull request #84
Opened 2017-02-06 10:14 UTC by FeditskiyRoman

2017-02-12 12:30 UTC, dmitrij-borchuk requested changes

2017-02-12 12:30 UTC, dmitrij-borchuk commented on dev/publicDev/admin.properties/style.scss
> +    display: block;
Rmove it

2017-02-12 12:30 UTC, dmitrij-borchuk commented on dev/publicDev/admin.properties/tpl.jade
> +            a.pa-img-wrap(href="#/photos/emergency_towing")
Move "a" to one layer deepped

2017-02-12 12:30 UTC, dmitrij-borchuk commented on dev/publicDev/emergencyTowing/service.js
> +    getEmergencyTowing: function() {
Move to "dev\publicDev\photos\dataProvider.js" and rename "dev\publicDev\photos\dataProvider.js" service please (wrong name "propertiesService").

2017-02-12 12:30 UTC, dmitrij-borchuk commented on dev/publicDev/photos/ctrl.js
> +    vm.emergencyTowing = [];
Can we use "vm.photos" for emergency towing?

2017-02-12 12:30 UTC, dmitrij-borchuk commented on dev/publicDev/photos/tpl.jade
> +        .message(ng-if="!vm.photos.length && !vm.emergencyTowing.length")
Can we use "vm.photos" for emergency towing?

2017-02-12 12:45 UTC, dmitrij-borchuk requested changes

2017-02-12 12:45 UTC, dmitrij-borchuk commented on dev/publicDev/photos/tpl.jade
> +          img(ng-src="{{photo}}")
"photo" is not image url

2017-02-13 08:49 UTC, FeditskiyRoman commented on dev/publicDev/admin.properties/style.scss
> +    display: block;
it should be because its tag 'a'

2017-02-13 19:45 UTC, dmitrij-borchuk commented on dev/publicDev/admin.properties/style.scss
> +    display: block;
Move "a" to one layer deepped

2017-02-14 08:53 UTC, FeditskiyRoman commented on dev/publicDev/photos/tpl.jade
> +        .message(ng-if="!vm.photos.length && !vm.emergencyTowing.length")
vm.photos it`s photo for one property and vm.emergencyTowing its for all property

2017-03-23 03:13 UTC, dmitrij-borchuk approved these changes

2017-03-23 03:13 UTC, merged