Cart 166 edit blocking towing
multicora/car-towing pull request #85
Opened 2017-02-06 14:04 UTC by FeditskiyRoman

2017-02-12 12:59 UTC, dmitrij-borchuk requested changes

2017-02-12 12:59 UTC, dmitrij-borchuk commented on dev/publicDev/managers-page/managers-controller.js
> +      vm.invalidDate = !(vm.hoursFrom && vm.minutesFrom && vm.hoursTo && vm.minutesTo);
Why do we need it in "vm"?

2017-02-12 12:59 UTC, dmitrij-borchuk commented on dev/publicDev/managers-page/managers-controller.js
> +            // vm.blockingData = {};
What for?

2017-02-12 12:59 UTC, dmitrij-borchuk commented on dev/publicDev/managers-page/managers-controller.js
> +        rulesDataService.updateBlocking(vm.newBlockingData, id)
Something wrong with indentation

2017-02-12 12:59 UTC, dmitrij-borchuk commented on dev/publicDev/managers-page/style.scss
> +  select {
Use class name

2017-02-13 08:34 UTC, FeditskiyRoman commented on dev/publicDev/managers-page/managers-controller.js
> +      vm.invalidDate = !(vm.hoursFrom && vm.minutesFrom && vm.hoursTo && vm.minutesTo);
because if it is in if it doesn't work

2017-02-15 20:29 UTC, dmitrij-borchuk approved these changes

2017-02-16 07:39 UTC, merged